---
AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket and DynamoDB for terraform remote state"

Parameters:
  BucketName:
    Description: "name of bucket"
    Type: String
  DynamoDBTableName:
    Description: "Name of the dynamodb table"
    Type: String
  TerraformUser:
    Description: "Terraform User"
    Type: String
    Default: "terraform"
  CloudformationUser:
    Description: "Cloudformation User"
    Type: String
    Default: "cloudformation"

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "test"
          Value: "value"
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DenyNotTerraformUsers"
            Effect: "Deny"
            Principal:
              AWS: "*"
            Action:
              - "*"
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}"
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Condition:
              StringEquals:
                "aws:PrincipalType":
                  - "User"
              StringNotLike:
                "aws:username":
                  - !Ref TerraformUser
                  - !Ref CloudformationUser
          - Sid: "TerraformPermisions"
            Effect: "Deny"
            Principal:
              AWS: "*"
            NotAction:
              - "s3:ListBucket"
              - "s3:GetBucketVersioning"
              - "s3:GetObject"
              - "s3:PutObject"
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Condition:
              StringEquals:
                "aws:PrincipalType": "User"
              StringLike:
                "aws:username":
                  - !Ref TerraformUser
  DynamoTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
Outputs:
  BucketName:
    Description: "name of bucket"
    Value: !Ref Bucket
  DynamoDBTableName:
    Description: "name of the dynamodb table"
    Value: !Ref DynamoTable
